unit TestIOUtils.FindFiles;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, IOUtils.FindFiles, System.SysUtils, System.Generics.Collections
  ;

type
  // Test methods for class TFileFinder

  TestTFileFinder = class(TTestCase)
  strict private
    FFileFinder: TFileFinder;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSearch;
  end;

implementation

procedure TestTFileFinder.SetUp;
begin
  FFileFinder := TFileFinder.Create;
end;

procedure TestTFileFinder.TearDown;
begin
  FFileFinder.Free;
  FFileFinder := nil;
end;

procedure TestTFileFinder.TestSearch;
var
  aQueue: TQueue<TSearchRec>;
begin
  // TODO: Setup method call parameters
  FFileFinder.Search(aQueue);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFileFinder.Suite);
end.

